apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config-env
  namespace: project
data:
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "ENV: %(asctime)s - %(name)s - %(levelname)s - %(message)s"
  IMG_URL: "https://picsum.photos/200"
  CACHE_DIR: "/usr/src/app/files/cache"
  TODO_APP_PORT: "3000"
  TODO_BACKEND_PORT: "3000"
  TODO_BACKEND_HOST: "127.0.0.1"
  TODO_APP_HOST: "127.0.0.1"
  TODO_BACKEND_URL: "http://127.0.0.1:8081"
  TODO_APP_URL: "http://127.0.0.1:8080"
  THE_PROJECT_ROOT: "/app"
