apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
annotations:
  traefik.ingress.kubernetes.io/rewrite-target: /
  traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
