apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: project
  name: todo-backend-ingress
spec:
  rules:
  - http:
      paths:
      - path: /todos
        pathType: Prefix
        backend:
          service:
            name: todo-backend-svc
            port:
              number: 4567
