apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: dwk-ping-pong-ingress
  annotations:
    ingress.gcp.kubernetes.io/healthcheck-path: "/pings"
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: ping-pong-svc
            port:
              number: 3456
      - path: /pings
        pathType: Prefix
        backend:
          service:
            name: ping-pong-svc
            port:
              number: 3456
