apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources: [../../base]
namePrefix: prod-


patches:
- path: todo-ingress-path-patch.yaml

images:
- name: arkb2023/broadcaster:latest
  newName: broadcaster:latest
  newTag: 0f71be809aa25ea04e67059524ce4b0da1b9f91c
