apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  rules:
  - http:
      paths:
      - path: /prod
        pathType: Prefix
        backend:
          service:
            name: todo-app-svc
            port:
              number: 1234
      - path: /prod/todos
        pathType: Prefix
        backend:
          service:
            name: todo-backend-svc
            port: 
              number: 4567

