apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
# PostgreSQL
- postgres-db-secret.yaml
- postgresql-configmap.yaml
- postgresql-service.yaml
- postgresql-statefulset.yaml

# Todo App
- todo-app-deployment.yaml
- todo-app-service.yaml

# Todo Backend
- todo-backend-deployment.yaml
- todo-backend-service.yaml

# ConfigMaps & CronJobs
- project-configmap.yaml
- cron_wiki_todo.yaml
