apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
# Service Account
- service-account.yaml

# Deployments
- greeter-dep-v1.yaml
- greeter-dep-v2.yaml

# Frontend Service
- greeter-svc.yaml

# Backend Services
- greeter-svc-v1.yaml
- greeter-svc-v2.yaml

# Split traffic routing rules
- greeter-route.yaml

