apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      # volumes:
      #   - name: shared-image
      #     persistentVolumeClaim:
      #       claimName: local-pv-claim
      containers:
        # - name: log-generator
        #   image: arkb2023/log-generator:1.10.2
        #   volumeMounts:
        #   - name: shared-image
        #     mountPath: /usr/src/app/files
        - name: log-reader
          image: arkb2023/log-reader:2.2
          # volumeMounts:
          # - name: shared-image
          #   mountPath: /usr/src/app/files

