apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
- namespace.yaml

# PostgreSQL
- postgresql-configmap.yaml
- postgresql-statefulset.yaml
- postgresql-service.yaml
- postgresql-init-script.yaml

# Ping-pong knative
- pingpong-knative-service.yaml

patches:
- path: postgresql-statefulset-patch.yaml